name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: release-downloader
        uses: robinraju/release-downloader@v1.6
        with:
          repository: cooklang/CookCLI
          latest: true

      - name: Extract and run CookCLI
        run: |
          sudo unzip $GITHUB_WORKSPACE/CookCLI_*_linux_amd64.zip -d /usr/local/bin/
          for RECIPE in $GITHUB_WORKSPACE/*.cook
          do
             cook recipe read "$RECIPE"
          done